In [5]:
import numpy as np

# Create a 1D NumPy array with integers from 1 to 20
arr = np.arange(1, 21)
print("Array:", arr)

# a. Calculate sum, mean, median, and standard deviation
arr_sum = np.sum(arr)
arr_mean = np.mean(arr)
arr_median = np.median(arr)
arr_std = np.std(arr)

print("Sum:", arr_sum)
print("Mean:", arr_mean)
print("Median:", arr_median)
print("Standard Deviation:", arr_std)

# b. Find indices of elements greater than 10
indices_gt_10 = np.where(arr > 10)[0]
print("Indices of elements > 10:", indices_gt_10)


Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Sum: 210
Mean: 10.5
Median: 10.5
Standard Deviation: 5.766281297335398
Indices of elements > 10: [10 11 12 13 14 15 16 17 18 19]


In [7]:
import numpy as np

# Create a 2D NumPy array of shape 4x4 with numbers from 1 to 16
arr_2d = np.arange(1, 17).reshape(4, 4)
print("2D Array:\n", arr_2d)

# a. Print the array (already printed above)

# b. Find the transpose of the array
transpose = arr_2d.T
print("Transpose:\n", transpose)

# c. Calculate row-wise and column-wise sums
row_sums = np.sum(arr_2d, axis=1)
col_sums = np.sum(arr_2d, axis=0)
print("Row-wise sums:", row_sums)
print("Column-wise sums:", col_sums)


2D Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Transpose:
 [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]
Row-wise sums: [10 26 42 58]
Column-wise sums: [28 32 36 40]


In [9]:
import numpy as np

# Create two 3x3 arrays filled with random integers between 1 and 20
np.random.seed(0)  # For reproducibility
arr1 = np.random.randint(1, 21, size=(3, 3))
arr2 = np.random.randint(1, 21, size=(3, 3))
print("Array 1:\n", arr1)
print("Array 2:\n", arr2)

# a. Element-wise addition, subtraction, and multiplication
add = arr1 + arr2
sub = arr1 - arr2
mul = arr1 * arr2
print("Element-wise Addition:\n", add)
print("Element-wise Subtraction:\n", sub)
print("Element-wise Multiplication:\n", mul)

# b. Dot product of the two arrays
# For 2D arrays, dot product is matrix multiplication
dot = np.dot(arr1, arr2)
print("Dot Product (Matrix Multiplication):\n", dot)


Array 1:
 [[13 16  1]
 [ 4  4  8]
 [10 20 19]]
Array 2:
 [[ 5  7 13]
 [ 2  7  8]
 [15 18  6]]
Element-wise Addition:
 [[18 23 14]
 [ 6 11 16]
 [25 38 25]]
Element-wise Subtraction:
 [[  8   9 -12]
 [  2  -3   0]
 [ -5   2  13]]
Element-wise Multiplication:
 [[ 65 112  13]
 [  8  28  64]
 [150 360 114]]
Dot Product (Matrix Multiplication):
 [[112 221 303]
 [148 200 132]
 [375 552 404]]


In [10]:
import numpy as np

# Create a 1D array of size 12
arr_1d = np.arange(1, 13)
print("Original 1D Array:", arr_1d)

# Reshape into a 3x4 2D array
arr_2d = arr_1d.reshape(3, 4)
print("Reshaped 3x4 Array:\n", arr_2d)

# Slice the first two rows and last two columns
sliced = arr_2d[:2, -2:]
print("First two rows and last two columns:\n", sliced)

Original 1D Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped 3x4 Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
First two rows and last two columns:
 [[3 4]
 [7 8]]
